language: d
sudo: false

matrix:
    include:
        - d: dmd
        - d: dmd-2.072.2
        - d: dmd-2.073.2
        - d: ldc

script:
  - dub test
  - dub run -c unittest-unthreaded --build=unittest
  - dub run -c unittest-light --build=unittest
